#!/bin/bash
_SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"
_PROJECT="$_SCRIPT_DIR"/FenixLib
_VERSION_FILE="$_SCRIPT_DIR"/version
_OUTPUT_DIR="$_SCRIPT_DIR"/nupkgs

_DEFAULT_VERSION_PREFIX=$(cat "$_VERSION_FILE")
_DEFAULT_VERSION_SUFFIX="dev+$(git rev-parse HEAD)"

_VERSION_PREFIX=${1:-$_DEFAULT_VERSION_PREFIX}
_VERSION_SUFFIX=${2-$_DEFAULT_VERSION_SUFFIX}

echo "Version Prefix: $_VERSION_PREFIX"
echo "Version Suffix: ${_VERSION_SUFFIX:-(empty)}"

dotnet pack /p:VersionPrefix="$_VERSION_PREFIX" \
    --version-suffix="$_VERSION_SUFFIX" \
    --output "$_OUTPUT_DIR" \
    "$_PROJECT"
