#!/bin/bash
_SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"

_outdir="$_SCRIPT_DIR"/nupkgs
_project="$_SCRIPT_DIR"/FenixLib
_version_file="$_SCRIPT_DIR"/version
dotnet pack /p:VersionPrefix="$(cat $_version_file)" --version-suffix="dev+$(git rev-parse HEAD)" --output "$_outdir" "$_project"
