#!/bin/bash
_SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"
_PROJECT="$_SCRIPT_DIR"/FenixLib
_VERSION_FILE="$_SCRIPT_DIR"/version

VERSION_PREFIX=${1:-"$(cat $_VERSION_FILE)"}
VERSION_SUFFIX=${2:-"dev+$(git rev-parse HEAD)"}

_outdir="$_SCRIPT_DIR"/nupkgs
dotnet pack /p:VersionPrefix="$VERSION_PREFIX" --version-suffix="$VERSION_SUFFIX" --output "$_outdir" "$_PROJECT"
