
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox mainContainer;
	
	private global::Gtk.VBox headerContainer;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.HSeparator hseparator1;
	
	private global::Gtk.HBox contentsContainer;
	
	private global::Gtk.VBox imageContainer;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Image previewImage;
	
	private global::Gtk.HBox mapButtonsContainer;
	
	private global::Gtk.Button openMapButton;
	
	private global::Gtk.VBox fpgContainer;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TreeView spriteAssortmentView;
	
	private global::Gtk.HBox fpgButtonsContainer;
	
	private global::Gtk.Button openFpgButton;
	
	private global::Gtk.VBox fntContainer;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.TreeView bitmapFontView;
	
	private global::Gtk.HBox fntButtonsContainer;
	
	private global::Gtk.Button openFntButton;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.AllowShrink = true;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.mainContainer = new global::Gtk.VBox ();
		this.mainContainer.Name = "mainContainer";
		this.mainContainer.Spacing = 6;
		this.mainContainer.BorderWidth = ((uint)(15));
		// Container child mainContainer.Gtk.Box+BoxChild
		this.headerContainer = new global::Gtk.VBox ();
		this.headerContainer.Name = "headerContainer";
		this.headerContainer.Spacing = 6;
		// Container child headerContainer.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.Xalign = 0F;
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Example of FenixLib use with Gtk</b>");
		this.label1.UseMarkup = true;
		this.headerContainer.Add (this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.headerContainer [this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child headerContainer.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.Xalign = 0F;
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Use one of the \"Open\" buttons below to open a PixTudio / BennuGD / Div resource.");
		this.headerContainer.Add (this.label2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.headerContainer [this.label2]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child headerContainer.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.headerContainer.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.headerContainer [this.hseparator1]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.mainContainer.Add (this.headerContainer);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.mainContainer [this.headerContainer]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child mainContainer.Gtk.Box+BoxChild
		this.contentsContainer = new global::Gtk.HBox ();
		this.contentsContainer.Name = "contentsContainer";
		this.contentsContainer.Spacing = 6;
		// Container child contentsContainer.Gtk.Box+BoxChild
		this.imageContainer = new global::Gtk.VBox ();
		this.imageContainer.Name = "imageContainer";
		this.imageContainer.Spacing = 6;
		// Container child imageContainer.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.Xalign = 0F;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Selected or loaded graphic preview:");
		this.label5.UseMarkup = true;
		this.imageContainer.Add (this.label5);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.imageContainer [this.label5]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child imageContainer.Gtk.Box+BoxChild
		this.previewImage = new global::Gtk.Image ();
		this.previewImage.WidthRequest = 400;
		this.previewImage.HeightRequest = 400;
		this.previewImage.Name = "previewImage";
		this.imageContainer.Add (this.previewImage);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.imageContainer [this.previewImage]));
		w6.Position = 1;
		// Container child imageContainer.Gtk.Box+BoxChild
		this.mapButtonsContainer = new global::Gtk.HBox ();
		this.mapButtonsContainer.Name = "mapButtonsContainer";
		this.mapButtonsContainer.Spacing = 6;
		// Container child mapButtonsContainer.Gtk.Box+BoxChild
		this.openMapButton = new global::Gtk.Button ();
		this.openMapButton.CanFocus = true;
		this.openMapButton.Name = "openMapButton";
		this.openMapButton.UseUnderline = true;
		this.openMapButton.Label = global::Mono.Unix.Catalog.GetString ("Open Map...");
		this.mapButtonsContainer.Add (this.openMapButton);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.mapButtonsContainer [this.openMapButton]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		this.imageContainer.Add (this.mapButtonsContainer);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.imageContainer [this.mapButtonsContainer]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		this.contentsContainer.Add (this.imageContainer);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.contentsContainer [this.imageContainer]));
		w9.Position = 0;
		// Container child contentsContainer.Gtk.Box+BoxChild
		this.fpgContainer = new global::Gtk.VBox ();
		this.fpgContainer.Name = "fpgContainer";
		this.fpgContainer.Spacing = 6;
		// Container child fpgContainer.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.Xalign = 0F;
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Fpg contents:");
		this.fpgContainer.Add (this.label3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.fpgContainer [this.label3]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child fpgContainer.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.spriteAssortmentView = new global::Gtk.TreeView ();
		this.spriteAssortmentView.CanFocus = true;
		this.spriteAssortmentView.Name = "spriteAssortmentView";
		this.GtkScrolledWindow.Add (this.spriteAssortmentView);
		this.fpgContainer.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.fpgContainer [this.GtkScrolledWindow]));
		w12.Position = 1;
		// Container child fpgContainer.Gtk.Box+BoxChild
		this.fpgButtonsContainer = new global::Gtk.HBox ();
		this.fpgButtonsContainer.Name = "fpgButtonsContainer";
		this.fpgButtonsContainer.Spacing = 6;
		// Container child fpgButtonsContainer.Gtk.Box+BoxChild
		this.openFpgButton = new global::Gtk.Button ();
		this.openFpgButton.CanFocus = true;
		this.openFpgButton.Name = "openFpgButton";
		this.openFpgButton.UseUnderline = true;
		this.openFpgButton.Label = global::Mono.Unix.Catalog.GetString ("Open Fpg...");
		this.fpgButtonsContainer.Add (this.openFpgButton);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.fpgButtonsContainer [this.openFpgButton]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		this.fpgContainer.Add (this.fpgButtonsContainer);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.fpgContainer [this.fpgButtonsContainer]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		this.contentsContainer.Add (this.fpgContainer);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.contentsContainer [this.fpgContainer]));
		w15.Position = 1;
		// Container child contentsContainer.Gtk.Box+BoxChild
		this.fntContainer = new global::Gtk.VBox ();
		this.fntContainer.Name = "fntContainer";
		this.fntContainer.Spacing = 6;
		// Container child fntContainer.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.Xalign = 0F;
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Fnt contents:");
		this.fntContainer.Add (this.label4);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.fntContainer [this.label4]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child fntContainer.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.bitmapFontView = new global::Gtk.TreeView ();
		this.bitmapFontView.CanFocus = true;
		this.bitmapFontView.Name = "bitmapFontView";
		this.GtkScrolledWindow1.Add (this.bitmapFontView);
		this.fntContainer.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.fntContainer [this.GtkScrolledWindow1]));
		w18.Position = 1;
		// Container child fntContainer.Gtk.Box+BoxChild
		this.fntButtonsContainer = new global::Gtk.HBox ();
		this.fntButtonsContainer.Name = "fntButtonsContainer";
		this.fntButtonsContainer.Spacing = 6;
		// Container child fntButtonsContainer.Gtk.Box+BoxChild
		this.openFntButton = new global::Gtk.Button ();
		this.openFntButton.CanFocus = true;
		this.openFntButton.Name = "openFntButton";
		this.openFntButton.UseUnderline = true;
		this.openFntButton.Label = global::Mono.Unix.Catalog.GetString ("Open Fnt...");
		this.fntButtonsContainer.Add (this.openFntButton);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.fntButtonsContainer [this.openFntButton]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		this.fntContainer.Add (this.fntButtonsContainer);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.fntContainer [this.fntButtonsContainer]));
		w20.Position = 2;
		w20.Expand = false;
		w20.Fill = false;
		this.contentsContainer.Add (this.fntContainer);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.contentsContainer [this.fntContainer]));
		w21.Position = 2;
		this.mainContainer.Add (this.contentsContainer);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.mainContainer [this.contentsContainer]));
		w22.Position = 1;
		this.Add (this.mainContainer);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 939;
		this.DefaultHeight = 675;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.openMapButton.Clicked += new global::System.EventHandler (this.OnOpenMapClicked);
		this.openFpgButton.Clicked += new global::System.EventHandler (this.OnOpenFpgClicked);
		this.openFntButton.Clicked += new global::System.EventHandler (this.OnOpenFntClicked);
	}
}
