
// This file has been generated by the GUI designer. Do not modify.

namespace FenixLibAndGtkExample
{
    public partial class MainWindow
    {
        private global::Gtk.VBox mainContainer;

        private global::Gtk.VBox headerContainer;

        private global::Gtk.Label label1;

        private global::Gtk.Label label2;

        private global::Gtk.HSeparator hseparator1;

        private global::Gtk.HBox contentsContainer;

        private global::Gtk.VBox imageContainer;

        private global::Gtk.Label label5;

        private global::Gtk.Image previewImage;

        private global::Gtk.HBox mapButtonsContainer;

        private global::Gtk.Button openMapButton;

        private global::Gtk.VBox fpgContainer;

        private global::Gtk.Label label3;

        private global::Gtk.ScrolledWindow GtkScrolledWindow;

        private global::Gtk.TreeView spriteAssortmentView;

        private global::Gtk.HBox fpgButtonsContainer;

        private global::Gtk.Button openFpgButton;

        private global::Gtk.VBox fntContainer;

        private global::Gtk.Label label4;

        private global::Gtk.ScrolledWindow GtkScrolledWindow1;

        private global::Gtk.TreeView bitmapFontView;

        private global::Gtk.HBox fntButtonsContainer;

        private global::Gtk.Button openFntButton;

        protected virtual void Build()
        {
            global::Stetic.Gui.Initialize(this);
            // Widget MainWindow
            this.Name = "MainWindow";
            this.Title = "Application";
            this.WindowPosition = ((global::Gtk.WindowPosition)(4));
            // Container child MainWindow.Gtk.Container+ContainerChild
            this.mainContainer = new global::Gtk.VBox();
            this.mainContainer.Name = "mainContainer";
            this.mainContainer.Spacing = 6;
            this.mainContainer.BorderWidth = ((uint)(15));
            // Container child mainContainer.Gtk.Box+BoxChild
            this.headerContainer = new global::Gtk.VBox();
            this.headerContainer.Name = "headerContainer";
            this.headerContainer.Spacing = 6;
            // Container child headerContainer.Gtk.Box+BoxChild
            this.label1 = new global::Gtk.Label();
            this.label1.Name = "label1";
            this.label1.Xalign = 0F;
            this.label1.LabelProp = "<b>Example of FenixLib use with Gtk</b>";
            this.label1.UseMarkup = true;
            this.headerContainer.Add(this.label1);
            // Container child headerContainer.Gtk.Box+BoxChild
            this.label2 = new global::Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Xalign = 0F;
            this.label2.LabelProp = "Use one of the \"Open\" buttons below to open a PixTudio / BennuGD / Div resource.";
            this.headerContainer.Add(this.label2);
            // Container child headerContainer.Gtk.Box+BoxChild
            this.hseparator1 = new global::Gtk.HSeparator();
            this.hseparator1.Name = "hseparator1";
            this.headerContainer.Add(this.hseparator1);
            this.mainContainer.Add(this.headerContainer);
            // Container child mainContainer.Gtk.Box+BoxChild
            this.contentsContainer = new global::Gtk.HBox();
            this.contentsContainer.Name = "contentsContainer";
            this.contentsContainer.Spacing = 6;
            // Container child contentsContainer.Gtk.Box+BoxChild
            this.imageContainer = new global::Gtk.VBox();
            this.imageContainer.Name = "imageContainer";
            this.imageContainer.Spacing = 6;
            // Container child imageContainer.Gtk.Box+BoxChild
            this.label5 = new global::Gtk.Label();
            this.label5.Name = "label5";
            this.label5.Xalign = 0F;
            this.label5.LabelProp = "Selected or loaded graphic preview:";
            this.label5.UseMarkup = true;
            this.imageContainer.Add(this.label5);
            // Container child imageContainer.Gtk.Box+BoxChild
            this.previewImage = new global::Gtk.Image();
            this.previewImage.WidthRequest = 400;
            this.previewImage.HeightRequest = 400;
            this.previewImage.Name = "previewImage";
            this.imageContainer.Add(this.previewImage);
            // Container child imageContainer.Gtk.Box+BoxChild
            this.mapButtonsContainer = new global::Gtk.HBox();
            this.mapButtonsContainer.Name = "mapButtonsContainer";
            this.mapButtonsContainer.Spacing = 6;
            // Container child mapButtonsContainer.Gtk.Box+BoxChild
            this.openMapButton = new global::Gtk.Button();
            this.openMapButton.CanFocus = true;
            this.openMapButton.Name = "openMapButton";
            this.openMapButton.UseUnderline = true;
            this.openMapButton.Label = "Open Map...";
            this.mapButtonsContainer.Add(this.openMapButton);
            this.imageContainer.Add(this.mapButtonsContainer);
            this.contentsContainer.Add(this.imageContainer);
            // Container child contentsContainer.Gtk.Box+BoxChild
            this.fpgContainer = new global::Gtk.VBox();
            this.fpgContainer.Name = "fpgContainer";
            this.fpgContainer.Spacing = 6;
            // Container child fpgContainer.Gtk.Box+BoxChild
            this.label3 = new global::Gtk.Label();
            this.label3.Name = "label3";
            this.label3.Xalign = 0F;
            this.label3.LabelProp = "Fpg contents:";
            this.fpgContainer.Add(this.label3);
            // Container child fpgContainer.Gtk.Box+BoxChild
            this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
            this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.spriteAssortmentView = new global::Gtk.TreeView();
            this.spriteAssortmentView.CanFocus = true;
            this.spriteAssortmentView.Name = "spriteAssortmentView";
            this.GtkScrolledWindow.Add(this.spriteAssortmentView);
            this.fpgContainer.Add(this.GtkScrolledWindow);
            // Container child fpgContainer.Gtk.Box+BoxChild
            this.fpgButtonsContainer = new global::Gtk.HBox();
            this.fpgButtonsContainer.Name = "fpgButtonsContainer";
            this.fpgButtonsContainer.Spacing = 6;
            // Container child fpgButtonsContainer.Gtk.Box+BoxChild
            this.openFpgButton = new global::Gtk.Button();
            this.openFpgButton.CanFocus = true;
            this.openFpgButton.Name = "openFpgButton";
            this.openFpgButton.UseUnderline = true;
            this.openFpgButton.Label = "Open Fpg...";
            this.fpgButtonsContainer.Add(this.openFpgButton);
            this.fpgContainer.Add(this.fpgButtonsContainer);
            this.contentsContainer.Add(this.fpgContainer);
            // Container child contentsContainer.Gtk.Box+BoxChild
            this.fntContainer = new global::Gtk.VBox();
            this.fntContainer.Name = "fntContainer";
            this.fntContainer.Spacing = 6;
            // Container child fntContainer.Gtk.Box+BoxChild
            this.label4 = new global::Gtk.Label();
            this.label4.Name = "label4";
            this.label4.Xalign = 0F;
            this.label4.LabelProp = "Fnt contents:";
            this.fntContainer.Add(this.label4);
            // Container child fntContainer.Gtk.Box+BoxChild
            this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
            this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
            this.GtkScrolledWindow1.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
            this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
            this.bitmapFontView = new global::Gtk.TreeView();
            this.bitmapFontView.CanFocus = true;
            this.bitmapFontView.Name = "bitmapFontView";
            this.GtkScrolledWindow1.Add(this.bitmapFontView);
            this.fntContainer.Add(this.GtkScrolledWindow1);
            // Container child fntContainer.Gtk.Box+BoxChild
            this.fntButtonsContainer = new global::Gtk.HBox();
            this.fntButtonsContainer.Name = "fntButtonsContainer";
            this.fntButtonsContainer.Spacing = 6;
            // Container child fntButtonsContainer.Gtk.Box+BoxChild
            this.openFntButton = new global::Gtk.Button();
            this.openFntButton.CanFocus = true;
            this.openFntButton.Name = "openFntButton";
            this.openFntButton.UseUnderline = true;
            this.openFntButton.Label = "Open Fnt...";
            this.fntButtonsContainer.Add(this.openFntButton);
            this.fntContainer.Add(this.fntButtonsContainer);
            this.contentsContainer.Add(this.fntContainer);
            this.mainContainer.Add(this.contentsContainer);
            this.Add(this.mainContainer);
            if ((this.Child != null))
            {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 939;
            this.DefaultHeight = 675;
            this.Show();
            this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
            this.openMapButton.Clicked += new global::System.EventHandler(this.OnOpenMapClicked);
            this.openFpgButton.Clicked += new global::System.EventHandler(this.OnOpenFpgClicked);
            this.openFntButton.Clicked += new global::System.EventHandler(this.OnOpenFntClicked);
        }
    }
}
