name: Build FenixLib

on:
  push:
    branches: main
  pull_request:

jobs:
  build:
    name: Build and Test FenixLib
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x.x
    - name: Restore dependencies
      run: dotnet restore fenixlib/FenixLib
    - name: Build
      run: dotnet build --no-restore fenixlib/FenixLib
    - name: Test
      run: dotnet test --no-build fenixlib/FenixLibTests
